name: App Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.MD'
      - '.github/**'

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Retrieve the secret and write it to a file
      env:
        SECRET_FILE: ${{ secrets.SECRET_FILE }}
      run: |
        echo $SECRET_FILE > ./src/secrets.json
        
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run app-test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: test-result/
        retention-days: 30        