name: App Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.MD'
      - '.github/**'
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Retrieve the secret and write it to a file
      env:
        SECRET_FILE: ${{ secrets.SECRET_FILE }}
      run: |
        echo $SECRET_FILE > ./src/secrets.json
        
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
  
    - name: Install dependencies
      run: npm ci

    #- name: Install Playwright Browsers
    #  run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run app-test

    - name: Show directory content
      run: | 
        ls -la test-result
        ls -la


    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: test-result/
        retention-days: 30        