# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linux Build

on:
  release:
    types: [created] 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v3
    - name: Retrieve the secret and write it to a file
      env:
        SECRET_FILE: ${{ secrets.SECRET_FILE }}
      run: |
        echo $SECRET_FILE > ./app/secrets.json

    - name: Retrieve the settings and write them to a file
      env:
        SETTINGS_FILE: ${{ secrets.SETTINGS_FILE }}
      run: |
        echo $SETTINGS_FILE > ./config/settings.json
        cat ./config/settings.json


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
       npm install       
       npm run installer-linux64
    
    - uses: actions/upload-artifact@v3
      with:
        name: AppImage
        path: |
          ./dist/*.AppImage
          ./dist/latest-linux.yml

    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ./dist/*.snap
